name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Describe your environment.
      placeholder: |
        - Platform, Python version and bigtree version
      value: |
        - Platform: [Windows / MacOS / Ubuntu]
        - Python version:
        - `bigtree` version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps or code to reproduce the behaviour.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
