name: 🚀 Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    attributes:
      label: Final Check
      description: Please confirm and check all the following options.
      options:
        - label: >
            I will watch this issue to stay updated with any comments or requests for additional information.
            I understand that timely responses will help in the evaluation and potential implementation of the feature.
          required: true
        - label: >
            I have reviewed the documentation and existing feature requests to ensure that my request is unique
            and hasn't been previously proposed.
          required: true
