package:
  name: bigtree
  version: 0.14.3

build:
  number: 3

requirements:
  run:
    - python

about:
  summary: Tree Implementation and Methods for Python, integrated with Python list, dictionary, and pandas DataFrame.
