{% set name = "bigtree" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_NUMBER') }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ environ.get('VERSION_NUMBER') }}.tar.gz
  sha256: {{ environ.get('SHA256') }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with Python list, dictionary, and pandas DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
