name: Upload Python Package to Conda

on:
  push:
    branches:
      - publish-to-conda

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      run: |
        conda install -c conda-forge conda-build
    - name: Publish to conda
      run: |
        cd conda
        conda build -c conda-forge --output-folder . .
        ls
        conda convert -p osx-64 noarch/*.tar.bz2
        conda convert -p win-64 noarch/*.tar.bz2
        anaconda upload --label main osx-64/*.tar.bz2
        anaconda upload --label main win-64/*.tar.bz2
