name: Upload Python Package to Conda

on:
  push:
    branches:
      - publish-to-conda

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: base
        python-version: 3.11
        channels: conda-forge
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true
        use-only-tar-bz2: true
    - name: Install conda-forge CI
      run: conda install -c conda-forge conda-smithy conda-forge-pinning
    - name: Build package
      run: conda-smithy rerender
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Re-render recipe"
        git push
#    - name: publish-to-conda
#      uses: maxibor/conda-package-publish-action@v1.1
#      with:
#        subDir: "conda"
#        AnacondaToken: ${{ secrets.CONDA_TOKEN }}
